name: Notificar Webhook Discord

on:
  push:
    paths:
      - 'status.json'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Enviar Embed a Discord Webhook
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "Ikgonavi Status Manager",
            "embeds": [{
              "title": "🟢 Datos del Sitio Actualizados",
              "description": "Se han modificado los scripts en **ikgmonxr.github.io/Library.lua**",
              "color": 5763719,
              "footer": { "text": "GitHub Pages Auto-Sync" },
              "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
            }]
          }' \
          "https://discord.com/api/webhooks/1539040228873076837/4vpo5dQgn3F1XXpallGCECAEomiaTEIWVSGd7-czYVgcCPPwr7fS-hdp-hKaZvSajuyG"
