name: Notificar Webhook Discord

on:
  push:
    paths:
      - 'status.json'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar Embed a Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "Ikgonavi Status Bot",
            "embeds": [{
              "title": "🟢 Datos del Sitio Actualizados",
              "description": "Se ha modificado status.json en ikgmonxr.github.io/Library.lua",
              "color": 5763719
            }]
          }' \
          "https://discord.com/api/webhooks/1539040228873076837/4vpo5dQgn3F1XXpallGCECAEomiaTEIWVSGd7-czYVgcCPPwr7fS-hdp-hKaZvSajuyG"
